import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'dart:math'; // 🚨 J.A.R.V.I.S: Enjin Rawak
import '../../core/theme/app_theme.dart';
import '../caregiver/caregiver_dashboard.dart';

class PatientSetupScreen extends StatefulWidget {
  const PatientSetupScreen({super.key});

  @override
  State<PatientSetupScreen> createState() => _PatientSetupScreenState();
}

class _PatientSetupScreenState extends State<PatientSetupScreen> {
  final _formKey = GlobalKey<FormState>();

  // --- CONTROLLERS ---
  final _caregiverNameController = TextEditingController();
  final _patientNameController = TextEditingController();
  final _ageController = TextEditingController();
  final _phoneController = TextEditingController();
  final _addressController = TextEditingController();
  final _conditionController = TextEditingController();
  final _secondaryContactController = TextEditingController();

  String _relationship = 'Parent';
  bool _isLoading = false;

  @override
  void dispose() {
    _caregiverNameController.dispose();
    _patientNameController.dispose();
    _ageController.dispose();
    _phoneController.dispose();
    _addressController.dispose();
    _conditionController.dispose();
    _secondaryContactController.dispose();
    super.dispose();
  }

  // 🚨 J.A.R.V.I.S: Protokol Jana Kod Unik (6 Aksara)
  String _generatePatientCode() {
    const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ123456789'; // Buang 'O' & '0' supaya tak keliru
    return List.generate(6, (index) => chars[Random().nextInt(chars.length)]).join();
  }

  Future<void> _saveProfile() async {
    if (_formKey.currentState!.validate()) {
      setState(() => _isLoading = true);

      final user = FirebaseAuth.instance.currentUser;
      if (user != null) {
        try {
          // 🚨 J.A.R.V.I.S: Jana kod auto kat sini!
          String autoGeneratedId = _generatePatientCode();

          await FirebaseFirestore.instance.collection('caregivers').doc(user.uid).set({
            'caregiverName': _caregiverNameController.text.trim(),
            'patientName': _patientNameController.text.trim(),
            'patientId': autoGeneratedId, // 👈 Kod auto-generate dah masuk!
            'relationship': _relationship,

            'emergencyContact': _phoneController.text.trim().isEmpty ? 'N/A' : _phoneController.text.trim(),
            'address': _addressController.text.trim().isEmpty ? 'Not Provided' : _addressController.text.trim(),
            'patientAge': _ageController.text.trim().isEmpty ? 'N/A' : _ageController.text.trim(),
            'patientCondition': _conditionController.text.trim().isEmpty ? 'General' : _conditionController.text.trim(),
            'secondaryContact': _secondaryContactController.text.trim().isEmpty ? 'N/A' : _secondaryContactController.text.trim(),

            'createdAt': FieldValue.serverTimestamp(),
            'lastUpdated': FieldValue.serverTimestamp(),
            'status': 'Active',
          }, SetOptions(merge: true));

          if (mounted) {
            setState(() => _isLoading = false);
            _showSuccessDialog(autoGeneratedId); // 🚨 Tunjuk kod kat user
          }
        } catch (e) {
          if (mounted) {
            setState(() => _isLoading = false);
            ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e'), backgroundColor: Colors.red));
          }
        }
      }
    }
  }

  // 🚨 J.A.R.V.I.S: Paparan Kod Lepas Berjaya
  void _showSuccessDialog(String code) {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => AlertDialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(24)),
        title: const Text('Setup Complete! 🦾', textAlign: TextAlign.center),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Text('Salin kod ini dan masukkan dalam aplikasi pesakit:', textAlign: TextAlign.center),
            const SizedBox(height: 15),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 10),
              decoration: BoxDecoration(color: AppTheme.primaryBlue.withOpacity(0.1), borderRadius: BorderRadius.circular(12)),
              child: Text(code, style: const TextStyle(fontSize: 28, fontWeight: FontWeight.bold, color: AppTheme.primaryBlue, letterSpacing: 4)),
            ),
          ],
        ),
        actions: [
          Center(
            child: ElevatedButton(
              onPressed: () => Navigator.pushReplacement(context, MaterialPageRoute(builder: (context) => const CaregiverDashboard())),
              style: ElevatedButton.styleFrom(backgroundColor: AppTheme.primaryBlue, shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12))),
              child: const Text('Enter Dashboard', style: TextStyle(color: Colors.white)),
            ),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF1F5F9),
      body: SafeArea(
        child: SingleChildScrollView(
          physics: const BouncingScrollPhysics(),
          padding: const EdgeInsets.symmetric(horizontal: 24.0, vertical: 20.0),
          child: Form(
            key: _formKey,
            child: Column(
              children: [
                const SizedBox(height: 20),
                const Text('Final Step! 🚀', style: TextStyle(fontSize: 32, fontWeight: FontWeight.bold, color: AppTheme.textDark)),
                const SizedBox(height: 8),
                Text('Creating your master profile and auto-ID.', style: TextStyle(fontSize: 16, color: Colors.blueGrey[400])),
                const SizedBox(height: 32),

                // --- SECTION: CAREGIVER ---
                _buildCard([
                  _buildSectionTitle('Caregiver Details', Icons.shield_outlined),
                  const SizedBox(height: 16),
                  _buildTextField(_caregiverNameController, 'Your Full Name', Icons.person_outline),
                  const SizedBox(height: 16),
                  _buildTextField(_phoneController, 'Primary Phone Number', Icons.phone, isMandatory: false),
                  const SizedBox(height: 16),
                  const Text('Relationship to Patient', style: TextStyle(fontSize: 13, fontWeight: FontWeight.w600, color: Colors.grey)),
                  const SizedBox(height: 8),
                  _buildDropdown(),
                ]),

                const SizedBox(height: 20),

                // --- SECTION: PATIENT ---
                _buildCard([
                  _buildSectionTitle('Patient Details', Icons.child_care),
                  const SizedBox(height: 16),
                  _buildTextField(_patientNameController, 'Patient Full Name', Icons.face),
                  const SizedBox(height: 16),
                  _buildTextField(_ageController, 'Patient Age', Icons.calendar_today, isNumber: true, isMandatory: false),
                  const SizedBox(height: 16),
                  _buildTextField(_conditionController, 'Medical Condition', Icons.medical_information, isMandatory: false),
                ]),

                const SizedBox(height: 20),

                // --- SECTION: CONTACT & LOCATION ---
                _buildCard([
                  _buildSectionTitle('Location (Optional)', Icons.location_on_outlined),
                  const SizedBox(height: 16),
                  _buildTextField(_addressController, 'Home Address', Icons.home_work_outlined, isMandatory: false),
                ]),

                const SizedBox(height: 40),

                SizedBox(
                  width: double.infinity,
                  height: 55,
                  child: ElevatedButton(
                    onPressed: _isLoading ? null : _saveProfile,
                    style: ElevatedButton.styleFrom(backgroundColor: AppTheme.primaryBlue, shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16))),
                    child: _isLoading
                        ? const CircularProgressIndicator(color: Colors.white)
                        : const Text('Complete Setup & Generate ID', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 16)),
                  ),
                ),
                const SizedBox(height: 30),
              ],
            ),
          ),
        ),
      ),
    );
  }

  // --- UI HELPERS (Kekalkan yang asal) ---
  Widget _buildCard(List<Widget> children) {
    return Container(
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(24), boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.03), blurRadius: 10, offset: const Offset(0, 5))]),
      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: children),
    );
  }

  Widget _buildSectionTitle(String title, IconData icon) {
    return Row(children: [Icon(icon, size: 20, color: AppTheme.primaryBlue), const SizedBox(width: 8), Text(title, style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: AppTheme.textDark))]);
  }

  Widget _buildTextField(TextEditingController controller, String hint, IconData icon, {bool isNumber = false, bool isMandatory = true}) {
    return TextFormField(
      controller: controller,
      keyboardType: isNumber ? TextInputType.number : TextInputType.text,
      decoration: InputDecoration(
        hintText: isMandatory ? hint : "$hint (Optional)",
        prefixIcon: Icon(icon, size: 20, color: Colors.grey.shade500),
        filled: true,
        fillColor: const Color(0xFFF8FAFC),
        border: OutlineInputBorder(borderRadius: BorderRadius.circular(16), borderSide: BorderSide.none),
        focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(16), borderSide: const BorderSide(color: AppTheme.primaryBlue, width: 1.5)),
      ),
      validator: (v) => (isMandatory && (v == null || v.trim().isEmpty)) ? 'Wajib isi babi!' : null,
    );
  }

  Widget _buildDropdown() {
    return DropdownButtonFormField<String>(
      value: _relationship,
      decoration: InputDecoration(filled: true, fillColor: const Color(0xFFF8FAFC), border: OutlineInputBorder(borderRadius: BorderRadius.circular(16), borderSide: BorderSide.none)),
      items: ['Parent', 'Teacher', 'Therapist', 'Guardian'].map((l) => DropdownMenuItem(value: l, child: Text(l))).toList(),
      onChanged: (v) => setState(() => _relationship = v!),
    );
  }
}