// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-m3nP0oxOG2GMRR0xGK1rCqDTV0YBlbU',
    appId: '1:953989401529:web:08baf22cb0bac0c0274468',
    messagingSenderId: '953989401529',
    projectId: 'pictospeak-fabb4',
    authDomain: 'pictospeak-fabb4.firebaseapp.com',
    storageBucket: 'pictospeak-fabb4.firebasestorage.app',
    measurementId: 'G-91DKKG0B0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUWU2SPqIRSzzjYSdi1QoJ_sT2MFCgHOE',
    appId: '1:953989401529:android:a7f6e4fb6b53a32b274468',
    messagingSenderId: '953989401529',
    projectId: 'pictospeak-fabb4',
    storageBucket: 'pictospeak-fabb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkZvul_b_5bwPtVu1trITxtCyGRTgHy6Y',
    appId: '1:953989401529:ios:bbd1aa13f381c3ba274468',
    messagingSenderId: '953989401529',
    projectId: 'pictospeak-fabb4',
    storageBucket: 'pictospeak-fabb4.firebasestorage.app',
    iosBundleId: 'com.example.pictoSpeak.pictospeak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkZvul_b_5bwPtVu1trITxtCyGRTgHy6Y',
    appId: '1:953989401529:ios:bbd1aa13f381c3ba274468',
    messagingSenderId: '953989401529',
    projectId: 'pictospeak-fabb4',
    storageBucket: 'pictospeak-fabb4.firebasestorage.app',
    iosBundleId: 'com.example.pictoSpeak.pictospeak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-m3nP0oxOG2GMRR0xGK1rCqDTV0YBlbU',
    appId: '1:953989401529:web:4e54ac6bdffdf610274468',
    messagingSenderId: '953989401529',
    projectId: 'pictospeak-fabb4',
    authDomain: 'pictospeak-fabb4.firebaseapp.com',
    storageBucket: 'pictospeak-fabb4.firebasestorage.app',
    measurementId: 'G-M1XB0PTM0W',
  );
}
